name: CI for some-aiohttp-middleware
on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install the project dependencies
        run: |
          pip install poetry
          poetry self add "poetry-dynamic-versioning[plugin]"
          poetry install --with test
      - name: Run tests and collect coverage
        run: |
          coverage run -m pytest
          coverage xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: .
          fail_ci_if_error: true
          files: ./coverage.xml